{% set name = "periodiq" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b849b04c47e3daa22fdf9fad87804255ff84aa9831f5b690fa1374d254a77cf9

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - periodiq = periodiq:entrypoint

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - dramatiq
    - pendulum

test:
  requires:
    - python {{ python_min }}
  imports:
    - periodiq
  commands:
    - periodiq -h

about:
  home: https://pypi.org/project/periodiq/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Simple Scheduler for Dramatiq Task Queue'
  dev_url: https://gitlab.com/bersace/periodiq

extra:
  recipe-maintainers:
    - mcs07
